[package]
name = "reredis"
version = "0.1.0"
authors = ["Jonathan <jofr@spreadshirt.net>"]
edition = "2018"

[dependencies]

[dev-dependencies]
quickcheck = "0.8.3"
quickcheck_macros = "0.8.0"
rand = "0.6.5"
tempfile = "3.0.8"
