[package]
name = "reredis"
version = "0.1.0"
authors = ["Jonathan <jofr@spreadshirt.net>"]
edition = "2018"

[dependencies]
void = "1.0.2"

[dev-dependencies]
quickcheck = "0.8.3"
quickcheck_macros = "0.8.0"
